#!/bin/sh
set -eu

export PORT="${PORT:-8080}"

envsubst '${PORT}' < /etc/nginx/http.d/default.conf > /tmp/default.conf
cp /tmp/default.conf /etc/nginx/http.d/default.conf

mkdir -p \
  storage/framework/cache \
  storage/framework/sessions \
  storage/framework/views \
  storage/logs \
  bootstrap/cache

chown -R www-data:www-data storage bootstrap/cache

php artisan config:clear
php artisan cache:clear
php artisan view:clear

php artisan config:cache
php artisan view:cache

exec /usr/bin/supervisord -c /etc/supervisord.conf
